### PR TITLE
Rename GITHUB_TOKEN env var to PERSONAL_ACCESS_TOKEN

### PR DESCRIPTION
**Pull request by marcohutzsch1234**
use PERSONAL_ACCESS_TOKEN to ensure the GITHUB_TOKEN env var default value is not used.

### CODE REVIEW

**Comment by marcohutzsch1234** [comment]
I've update the PR with a second change.
If the IAM_USERNAME env var is not set, the IAM user is read from the AWS credentials asking the AWS api for himself.

**Comment by marcohutzsch1234** [comment]
@kneemaa I see this PR is still open, do you still maintain the repository?

**Comment by kneemaa** [comment]
@marcohutzsch1234 apologies i just saw this as i was never assigned the PR. I can take a look at this later this week and test it in my environment before approving and merging.

**Comment by kneemaa** [comment]
@marcohutzsch1234 

The `who_ami_()` functionality is great.

Why do we need to "use PERSONAL_ACCESS_TOKEN to ensure the GITHUB_TOKEN env var default value is not used."?

**Comment by marcohutzsch1234** [comment]
Hi @kneemaa ,
der GITHUB_TOKEN var cannot be set from outside. If you pass a value for the var in an action, the value is not used. Github prevents action runs from overriding any GITHUB_* env var. The existing GITHUB_TOKEN has only access to the repository, where the pipeline lives in. When you want to update the secrets for a couple of repos, it fails with GITHUB_TOKEN because the GITHUB_TOKEN has no access to other repos.
Hth!

Marco

**Comment by marcohutzsch1234** [comment]
thanks for merging!

**Pull request merged**
